const mongoose = require("mongoose");

const MONGODB_URI = "mongodb+srv://sasukeuchi8989_db_user:ObPACEfzWpCIApii@bibliotecante.a512mpr.mongodb.net/bibliotecaNTE?appName=bibliotecaNTE";

const bookSchema = new mongoose.Schema({
    id: { type: String, required: true, unique: true },
    title: String,
    author: String,
    status: { type: String, default: "Disponível" }
});

const Book = mongoose.model("Book", bookSchema);

const books = [
{"id":"8951T999A1 ed. ex.1","title":"A ARTE DA GUERRA","author":"SUNTZU","status":"Disponível"},
{"id":"028.5R484A1 ed. ex.1","title":"A ÁRVORE DOS MEUS QUINTAIS","author":"JONAS RIBEIRO","status":"Disponível"},
{"id":"028.5R484A1 ed. ex.2","title":"A ÁRVORE DOS MEUS QUINTAIS","author":"JONAS RIBEIRO","status":"Disponível"},
{"id":"028.5R484A1 ed. ex.3","title":"A ÁRVORE DOS MEUS QUINTAIS","author":"JONAS RIBEIRO","status":"Disponível"},
{"id":"028.5C578B1 ed. ex.1","title":"A BELA E A FERA","author":"CIRANDA CULTURAL","status":"Disponível"},
{"id":"028.5C578B1 ed. ex.2","title":"A BELA E A FERA","author":"CIRANDA CULTURAL","status":"Disponível"},
{"id":"028.5C578B1 ed. ex.3","title":"A BELA E A FERA","author":"CIRANDA CULTURAL","status":"Disponível"},
{"id":"028.5C578B1 ed. ex.4","title":"A BELA E A FERA","author":"CIRANDA CULTURAL","status":"Disponível"},
{"id":"028.5C578B1 ed. ex.5","title":"A BELA E A FERA","author":"CIRANDA CULTURAL","status":"Disponível"},
{"id":"028.5C578B1 ed. ex.6","title":"A BELA E A FERA","author":"CIRANDA CULTURAL","status":"Disponível"},
{"id":"028.5P579B2 ed. ex.1","title":"A BORBOLETA VIOLETA","author":"MARI PIAIA","status":"Disponível"},
{"id":"8917P987D1 ed. ex.1","title":"A DAMA DE ESPADAS","author":"ALEXANDRE PUSHKIN","status":"Disponível"},
{"id":"8917P987D1 ed. ex.2","title":"A DAMA DE ESPADAS","author":"ALEXANDRE PUSHKIN","status":"Disponível"},
{"id":"8917P987D1 ed. ex.3","title":"A DAMA DE ESPADAS","author":"ALEXANDRE PUSHKIN","status":"Disponível"},
{"id":"IR820W671D1 ed. ex.1","title":"A DECADÊNCIA DA MENTIRA","author":"OSCAR WILDE","status":"Disponível"},
{"id":"IR820W671D1 ed. ex.2","title":"A DECADÊNCIA DA MENTIRA","author":"OSCAR WILDE","status":"Disponível"},
{"id":"IR820W671D1 ed. ex.3","title":"A DECADÊNCIA DA MENTIRA","author":"OSCAR WILDE","status":"Disponível"},
{"id":"851A411D1 ed. ex.1","title":"A DIVINA COMÉDIA - PARAÍSO","author":"DANTE ALICHIERI","status":"Disponível"},
{"id":"851A411D1 ed. ex.2","title":"A DIVINA COMÉDIA - PARAÍSO","author":"DANTE ALICHIERI","status":"Disponível"},
{"id":"851A411D1 ed. ex.3","title":"A DIVINA COMÉDIA - PARAÍSO","author":"DANTE ALICHIERI","status":"Disponível"},
{"id":"B8693G963E1 ed. ex.1","title":"A ESCRAVA ISAURA","author":"BERNARDO GUIMARÃES","status":"Disponível"},
{"id":"B8693G963E1 ed. ex.2","title":"A ESCRAVA ISAURA","author":"BERNARDO GUIMARÃES","status":"Disponível"},
{"id":"B8693G963E1 ed. ex.3","title":"A ESCRAVA ISAURA","author":"BERNARDO GUIMARÃES","status":"Disponível"},
{"id":"B8693A447F1 ed. ex.1","title":"A FALÊNCIA","author":"JULIA LOPES DE ALMEIDA","status":"Disponível"},
{"id":"B8693A447F1 ed. ex.2","title":"A FALÊNCIA","author":"JULIA LOPES DE ALMEIDA","status":"Disponível"},
{"id":"B8693A447F1 ed. ex.3","title":"A FALÊNCIA","author":"JULIA LOPES DE ALMEIDA","status":"Disponível"},
{"id":"B8693S848M1 ed. ex.1","title":"A MÃO E A LUVA","author":"MACHADO DE ASSIS","status":"Disponível"},
{"id":"833K11M1 ed. ex.1","title":"A METAMORFOSE","author":"FRANZ KAFKA","status":"Disponível"},
{"id":"028.5G936M ed. ex.1","title":"A MORENA DA RENDA VERMELHA","author":"FABIANA GUIMARÃES","status":"Disponível"},
{"id":"028.5G936M ed. ex.2","title":"A MORENA DA RENDA VERMELHA","author":"FABIANA GUIMARÃES","status":"Disponível"},
{"id":"028.5G936M ed. ex.3","title":"A MORENA DA RENDA VERMELHA","author":"FABIANA GUIMARÃES","status":"Disponível"},
{"id":"833H766O1 ed. ex.1","title":"A ODISSEIA","author":"HOMERO","status":"Disponível"},
{"id":"028.5C578P1 ed. ex.1","title":"A PEQUENA SEREIA","author":"CIRANDA CULTURAL","status":"Disponível"},
{"id":"028.5C578P1 ed. ex.2","title":"A PEQUENA SEREIA","author":"CIRANDA CULTURAL","status":"Disponível"},
{"id":"028.5C578P1 ed. ex.3","title":"A PEQUENA SEREIA","author":"CIRANDA CULTURAL","status":"Disponível"},
{"id":"028.5C578P1 ed. ex.4","title":"A PEQUENA SEREIA","author":"CIRANDA CULTURAL","status":"Disponível"},
{"id":"028.5C578P1 ed. ex.5","title":"A PEQUENA SEREIA","author":"CIRANDA CULTURAL","status":"Disponível"},
{"id":"028.5C578P1 ed. ex.6","title":"A PEQUENA SEREIA","author":"CIRANDA CULTURAL","status":"Disponível"},
{"id":"8693Q3R2 ed. ex.1","title":"A RELÍQUIA","author":"EÇA DE QUEIRÓS","status":"Disponível"},
{"id":"8693Q3R2 ed. ex.2","title":"A RELÍQUIA","author":"EÇA DE QUEIRÓS","status":"Disponível"},
{"id":"8693Q3R2 ed. ex.3","title":"A RELÍQUIA","author":"EÇA DE QUEIRÓS","status":"Disponível"},
{"id":"155.4J13T1 ed. ex.1","title":"A TIMIDEZ NÃO É UM PROBLEMA","author":"J. S. JACKSON","status":"Disponível"},
{"id":"155.4J13T1 ed. ex.2","title":"A TIMIDEZ NÃO É UM PROBLEMA","author":"J. S. JACKSON","status":"Disponível"},
{"id":"155.4J13T1 ed. ex.3","title":"A TIMIDEZ NÃO É UM PROBLEMA","author":"J. S. JACKSON","status":"Disponível"},
{"id":"180S475V1 ed. ex.1","title":"A VIDA FELIZ","author":"SÊNECA","status":"Disponível"},
{"id":"028.5M386A1 ed. ex.1","title":"ABAIXO A DITADURA","author":"CLÁUDIO MARTINS","status":"Disponível"},
{"id":"028.5M386A1 ed. ex.2","title":"ABAIXO A DITADURA","author":"CLÁUDIO MARTINS","status":"Disponível"},
{"id":"028.5M386A1 ed. ex.3","title":"ABAIXO A DITADURA","author":"CLÁUDIO MARTINS","status":"Disponível"},
{"id":"028.5C842A1 ed. ex.1","title":"ABECEDÁRIO AFRO DE POESIA","author":"SILVIO COSTTA","status":"Disponível"},
{"id":"028.5C842A1 ed. ex.2","title":"ABECEDÁRIO AFRO DE POESIA","author":"SILVIO COSTTA","status":"Disponível"},
{"id":"028.5C842A1 ed. ex.3","title":"ABECEDÁRIO AFRO DE POESIA","author":"SILVIO COSTTA","status":"Disponível"},
{"id":"028.5F853A1 ed. ex.1","title":"ACADEMIA DOS ABRAÇOS","author":"CIRANDA CULTURAL","status":"Disponível"},
{"id":"028.5C578A1 ed. ex.4","title":"ADA LOVELACE","author":"CIRANDA CULTURAL","status":"Disponível"},
{"id":"028.5C578A1 ed. ex.5","title":"ADA LOVELACE","author":"CIRANDA CULTURAL","status":"Disponível"},
{"id":"028.5C578A1 ed. ex.6","title":"ADA LOVELACE","author":"CIRANDA CULTURAL","status":"Disponível"},
{"id":"028.5P349A1 ed. ex.4","title":"AJUDAR","author":"PÉ DA LETRA","status":"Disponível"},
{"id":"028.5P349A1 ed. ex.5","title":"AJUDAR","author":"PÉ DA LETRA","status":"Disponível"},
{"id":"028.5P349A1 ed. ex.6","title":"AJUDAR","author":"PÉ DA LETRA","status":"Disponível"},
{"id":"028.5C578A1 ed. ex.1","title":"ALICE NO PAÍS DAS MARAVILHAS","author":"CIRANDA CULTURAL","status":"Disponível"},
{"id":"028.5C578A1 ed. ex.2","title":"ALICE NO PAÍS DAS MARAVILHAS","author":"CIRANDA CULTURAL","status":"Disponível"},
{"id":"028.5C578A1 ed. ex.3","title":"ALICE NO PAÍS DAS MARAVILHAS","author":"CIRANDA CULTURAL","status":"Disponível"},
{"id":"B8693A554A1 ed. ex.1","title":"AMAR, VERBO INTRANSITIVO","author":"MARIO DE ANDRADE","status":"Disponível"},
{"id":"B8693A554A1 ed. ex.2","title":"AMAR, VERBO INTRANSITIVO","author":"MARIO DE ANDRADE","status":"Disponível"},
{"id":"B8693A554A1 ed. ex.3","title":"AMAR, VERBO INTRANSITIVO","author":"MARIO DE ANDRADE","status":"Disponível"},
{"id":"028.5P349A1 ed. ex.1","title":"AMIGOS","author":"PÉ DA LETRA","status":"Disponível"},
{"id":"028.5P349A1 ed. ex.2","title":"AMIGOS","author":"PÉ DA LETRA","status":"Disponível"},
{"id":"028.5P349A1 ed. ex.3","title":"AMIGOS","author":"PÉ DA LETRA","status":"Disponível"},
{"id":"028.5C578A1 ed. ex.7","title":"AMIGOS DO ESPAÇO","author":"CIRANDA CULTURAL","status":"Disponível"},
{"id":"028.5C578A1 ed. ex.8","title":"AMIGOS DO ESPAÇO","author":"CIRANDA CULTURAL","status":"Disponível"},
{"id":"028.5C578A1 ed. ex.9","title":"ANIMAIS","author":"CIRANDA CULTURAL","status":"Disponível"},
{"id":"028.5C578A1 ed. ex.10","title":"ANIMAIS","author":"CIRANDA CULTURAL","status":"Disponível"},
{"id":"028.5C578A1 ed. ex.11","title":"ANIMAIS","author":"CIRANDA CULTURAL","status":"Disponível"},
{"id":"813T969A1 ed. ex.1","title":"AS AVENTURAS DE TOM SAWYER","author":"MARK TWAIN","status":"Disponível"},
{"id":"813T969A1 ed. ex.2","title":"AS AVENTURAS DE TOM SAWYER","author":"MARK TWAIN","status":"Disponível"},
{"id":"813T969A1 ed. ex.3","title":"AS AVENTURAS DE TOM SAWYER","author":"MARK TWAIN","status":"Disponível"},
{"id":"IR820L433C1 ed. ex.1","title":"CARMILLA A VAMPIRA DE KARNSTEIN","author":"JOSEPH SHERIDAN","status":"Disponível"},
{"id":"IR820L433C1 ed. ex.2","title":"CARMILLA A VAMPIRA DE KARNSTEIN","author":"JOSEPH SHERIDAN","status":"Disponível"},
{"id":"IR820L433C1 ed. ex.3","title":"CARMILLA A VAMPIRA DE KARNSTEIN","author":"JOSEPH SHERIDAN","status":"Disponível"},
{"id":"187E64C1 ed. ex.1","title":"CARTA A MENECEU SOBRE A FELICIDADE E OUTRAS CARTASS","author":"EPICURO","status":"Disponível"},
{"id":"187E64C1 ed. ex.2","title":"CARTA A MENECEU SOBRE A FELICIDADE E OUTRAS CARTASS","author":"EPICURO","status":"Disponível"},
{"id":"187E64C1 ed. ex.3","title":"CARTA A MENECEU SOBRE A FELICIDADE E OUTRAS CARTASS","author":"EPICURO","status":"Disponível"},
{"id":"B8693L796C1 ed. ex.1","title":"CIDADES MORTAS E OUTROS CONTOS","author":"MONTEIRO LOBATO","status":"Disponível"},
{"id":"B8693L796C1 ed. ex.2","title":"CIDADES MORTAS E OUTROS CONTOS","author":"MONTEIRO LOBATO","status":"Disponível"},
{"id":"B8693L796C1 ed. ex.3","title":"CIDADES MORTAS E OUTROS CONTOS","author":"MONTEIRO LOBATO","status":"Disponível"},
{"id":"240A275C1 ed. ex.1","title":"CONFISSÕES","author":"AGASTINHO","status":"Disponível"},
{"id":"240A275C1 ed. ex.2","title":"CONFISSÕES","author":"AGASTINHO","status":"Disponível"},
{"id":"240A275C1 ed. ex.3","title":"CONFISSÕES","author":"AGASTINHO","status":"Disponível"},
{"id":"B8693A55C1 ed. ex.1","title":"CONTOS NOVOS","author":"MÁRIO ANDRADE","status":"Disponível"},
{"id":"B8693A55C1 ed. ex.2","title":"CONTOS NOVOS","author":"MÁRIO ANDRADE","status":"Disponível"},
{"id":"B8693A55C1 ed. ex.3","title":"CONTOS NOVOS","author":"MÁRIO ANDRADE","status":"Disponível"},
{"id":"89173T654D1 ed. ex.1","title":"DE QUANTA TERRA PRECISA UM HOMEM","author":"LIEV TOLSTÓI","status":"Disponível"},
{"id":"89173T654D1 ed. ex.2","title":"DE QUANTA TERRA PRECISA UM HOMEM","author":"LIEV TOLSTÓI","status":"Disponível"},
{"id":"89173T654D1 ed. ex.3","title":"DE QUANTA TERRA PRECISA UM HOMEM","author":"LIEV TOLSTÓI","status":"Disponível"},
{"id":"823O79D1 ed. ex.1","title":"DENTRO DA BALELA E OUTROS ENSAIOS","author":"GEORGE ORWELL","status":"Disponível"},
{"id":"823O79D1 ed. ex.2","title":"DENTRO DA BALELA E OUTROS ENSAIOS","author":"GEORGE ORWELL","status":"Disponível"},
{"id":"823O79D1 ed. ex.3","title":"DENTRO DA BALELA E OUTROS ENSAIOS","author":"GEORGE ORWELL","status":"Disponível"},
{"id":"200.71E57D1 ed. ex.1","title":"DEUS É MEU AMIGO","author":"LISA O. ENGELHARDT","status":"Disponível"},
{"id":"200.71E57D1 ed. ex.2","title":"DEUS É MEU AMIGO","author":"LISA O. ENGELHARDT","status":"Disponível"},
{"id":"200.71E57D1 ed. ex.3","title":"DEUS É MEU AMIGO","author":"LISA O. ENGELHARDT","status":"Disponível"},
{"id":"413071C578D1 ed. ex.1","title":"DICIONARIO ESCOLAR","author":"CIRANDA CULTURAL","status":"Disponível"},
{"id":"413071C578D1 ed. ex.2","title":"DICIONARIO ESCOLAR","author":"CIRANDA CULTURAL","status":"Disponível"},
{"id":"B8693A368D1 ed. ex.1","title":"DIVA","author":"JOSÉ DE ALENCAR","status":"Disponível"},
{"id":"B8693A368D1 ed. ex.2","title":"DIVA","author":"JOSÉ DE ALENCAR","status":"Disponível"},
{"id":"B8693A368D1 ed. ex.3","title":"DIVA","author":"JOSÉ DE ALENCAR","status":"Disponível"},
{"id":"851411D1 ed. ex.1","title":"DIVINA COMÉDIA - PURGATÓRIO","author":"DANTE ALICHIERI","status":"Disponível"},
{"id":"851411D1 ed. ex.2","title":"DIVINA COMÉDIA - PURGATÓRIO","author":"DANTE ALICHIERI","status":"Disponível"},
{"id":"851411D1 ed. ex.3","title":"DIVINA COMÉDIA - PURGATÓRIO","author":"DANTE ALICHIERI","status":"Disponível"},
{"id":"320R864D1 ed. ex.1","title":"DO CONTRATO SOCIAL","author":"JEAN-JACQUES ROUSSEAU","status":"Disponível"},
{"id":"320R864D1 ed. ex.2","title":"DO CONTRATO SOCIAL","author":"JEAN-JACQUES ROUSSEAU","status":"Disponível"},
{"id":"320R864D1 ed. ex.3","title":"DO CONTRATO SOCIAL","author":"JEAN-JACQUES ROUSSEAU","status":"Disponível"},
{"id":"B8693A848D1 ed. ex.1","title":"DOM CASMURRO","author":"MACHADO DE ASSIS","status":"Disponível"},
{"id":"B8691A474E1 ed. ex.1","title":"ESPUMAS FLUTUANTES","author":"CASTRO ALVES","status":"Disponível"},
{"id":"B8691A474E1 ed. ex.2","title":"ESPUMAS FLUTUANTES","author":"CASTRO ALVES","status":"Disponível"},
{"id":"B8691A474E1 ed. ex.3","title":"ESPUMAS FLUTUANTES","author":"CASTRO ALVES","status":"Disponível"},
{"id":"100A717E1 ed. ex.1","title":"ÉTICA A NICÔMACO","author":"ARISTÓTALES","status":"Disponível"},
{"id":"100A717E1 ed. ex.2","title":"ÉTICA A NICÔMACO","author":"ARISTÓTALES","status":"Disponível"},
{"id":"B8693A662C1 ed. ex.1","title":"GRAÇA ARANHA CANAÃ","author":"PRINCIPIS","status":"Disponível"},
{"id":"B8693A662C1 ed. ex.2","title":"GRAÇA ARANHA CANAÃ","author":"PRINCIPIS","status":"Disponível"},
{"id":"B8693A662C1 ed. ex.3","title":"GRAÇA ARANHA CANAÃ","author":"PRINCIPIS","status":"Disponível"},
{"id":"0285R27RI1 ed. ex.1","title":"ÍRIS E ISAQUE","author":"CATHERINE RAYNER","status":"Disponível"},
{"id":"0285R27RI1 ed. ex.2","title":"ÍRIS E ISAQUE","author":"CATHERINE RAYNER","status":"Disponível"},
{"id":"0285R27RI1 ed. ex.3","title":"ÍRIS E ISAQUE","author":"CATHERINE RAYNER","status":"Disponível"},
{"id":"155.4G313M1 ed. ex.1","title":"MEU CORPO É ESPECIAL","author":"CYNTHIA G","status":"Disponível"},
{"id":"B8693A848A3 ed. ex.1","title":"O ALIENISTA","author":"MACHADO DE ASSIS","status":"Disponível"},
{"id":"B8693A848A3 ed. ex.2","title":"O ALIENISTA","author":"MACHADO DE ASSIS","status":"Disponível"},
{"id":"B8693A848A3 ed. ex.3","title":"O ALIENISTA","author":"MACHADO DE ASSIS","status":"Disponível"},
{"id":"184P716B1 ed. ex.1","title":"O BANQUETE","author":"PLATÃO","status":"Disponível"},
{"id":"184P716B1 ed. ex.2","title":"O BANQUETE","author":"PLATÃO","status":"Disponível"},
{"id":"184P716B1 ed. ex.3","title":"O BANQUETE","author":"PLATÃO","status":"Disponível"},
{"id":"833K11C1 ed. ex.1","title":"O CASTELO","author":"FRANZ KAFKA","status":"Disponível"},
{"id":"833K11C1 ed. ex.2","title":"O CASTELO","author":"FRANZ KAFKA","status":"Disponível"},
{"id":"833K11C1 ed. ex.3","title":"O CASTELO","author":"FRANZ KAFKA","status":"Disponível"},
{"id":"813P743C1 ed. ex.1","title":"O CORVO","author":"EDGAR ALLAN","status":"Disponível"},
{"id":"813P743C1 ed. ex.2","title":"O CORVO","author":"EDGAR ALLAN","status":"Disponível"},
{"id":"813C549D1 ed. ex.1","title":"O DESPERTAR","author":"KATE CHOPIN","status":"Disponível"},
{"id":"813C549D1 ed. ex.2","title":"O DESPERTAR","author":"KATE CHOPIN","status":"Disponível"},
{"id":"89173D724E1 ed. ex.1","title":"O ETERNO MARIDO","author":"FIÓDOR DOSTOIÉVSKI","status":"Disponível"},
{"id":"89173D724E1 ed. ex.2","title":"O ETERNO MARIDO","author":"FIÓDOR DOSTOIÉVSKI","status":"Disponível"},
{"id":"IR820W671F1 ed. ex.1","title":"O FANTASMA DE CANTERVILLE","author":"OSCAR WILDE","status":"Disponível"},
{"id":"840D886B1 ed. ex.1","title":"OS BÓRGIAS","author":"ALEXANDRE DUMAS","status":"Disponível"},
{"id":"840D886B1 ed. ex.2","title":"OS BÓRGIAS","author":"ALEXANDRE DUMAS","status":"Disponível"},
{"id":"840D886B1 ed. ex.3","title":"OS BÓRGIAS","author":"ALEXANDRE DUMAS","status":"Disponível"},
{"id":"B8693B273B1 ed. ex.1","title":"OS BRUZUNDANGAS","author":"LIMA BARRETO","status":"Disponível"},
{"id":"B8693B273B1 ed. ex.2","title":"OS BRUZUNDANGAS","author":"LIMA BARRETO","status":"Disponível"},
{"id":"823A933R1 ed. ex.1","title":"RAZÃO E SENSIBILIDADE","author":"JANE AUSTEN","status":"Disponível"},
{"id":"2995T999T1ED ed. ex.1","title":"TAO TE CHING - O LIVRO DO CAMINHO E DA VIRTUDE","author":"LAO TZU","status":"Disponível"},
{"id":"2995T999T1ED ed. ex.2","title":"TAO TE CHING - O LIVRO DO CAMINHO E DA VIRTUDE","author":"LAO TZU","status":"Disponível"},
{"id":"2995T999T1ED ed. ex.3","title":"TAO TE CHING - O LIVRO DO CAMINHO E DA VIRTUDE","author":"LAO TZU","status":"Disponível"},
{"id":"B8693A368T3 ed. ex.1","title":"TIL","author":"JOSÉ DE ALENCAR","status":"Disponível"},
{"id":"B8693A368T3 ed. ex.2","title":"TIL","author":"JOSÉ DE ALENCAR","status":"Disponível"},
{"id":"B8693A368T3 ed. ex.3","title":"TIL","author":"JOSÉ DE ALENCAR","status":"Disponível"},
{"id":"823D548C1 ed. ex.1","title":"UM CONTO DE DUAS CIDADES","author":"CHARLES DICKENS","status":"Disponível"},
{"id":"823D548C1 ed. ex.2","title":"UM CONTO DE DUAS CIDADES","author":"CHARLES DICKENS","status":"Disponível"},
{"id":"823D548C1 ed. ex.3","title":"UM CONTO DE DUAS CIDADES","author":"CHARLES DICKENS","status":"Disponível"},
{"id":"B8693L796U1 ed. ex.1","title":"URUPÊS","author":"MONTEIRO LOBATO","status":"Disponível"},
{"id":"B8693L796U1 ed. ex.2","title":"URUPÊS","author":"MONTEIRO LOBATO","status":"Disponível"},
{"id":"B8693L796U1 ed. ex.3","title":"URUPÊS","author":"MONTEIRO LOBATO","status":"Disponível"}
];

async function importar() {
    await mongoose.connect(MONGODB_URI);
    console.log("Conectado!");

    let inseridos = 0;
    let ignorados = 0;

    for (const book of books) {
        try {
            await Book.create(book);
            inseridos++;
        } catch (e) {
            ignorados++;
        }
    }

    console.log(`✅ ${inseridos} livros inseridos, ${ignorados} ignorados (já existiam).`);
    await mongoose.disconnect();
}

importar();
